# Honest-GAP Prediction IdentityThis notebook demonstrates why ordinary RF-GAP proximities are not prediction-preserving for `HonestForestClassifier`, then checks the Honest-specific `prox_method="honest_gap"` adapter.

In [ ]:
from forestgap import Proximity, embed, get_prototypes, impute, local_feature_importance, outlier_scoresclass _LegacyProximityModel:    def __init__(self, proximity):        self._proximity = proximity    def fit(self, X, y=None, **fit_kwargs):        self._proximity.fit(X, y, **fit_kwargs)        return self    def attach(self, X, y=None):        self._proximity.attach(X, y)        return self    def set_params(self, **params):        prox_params = {}        for key in ("relation", "prox_method", "matrix_type", "non_zero_diagonal", "symm_mode", "max_normalize", "random_state"):            if key in params:                prox_params[key] = params.pop(key)        if params:            self._proximity.estimator.set_params(**params)        if "prox_method" in prox_params and "relation" not in prox_params:            prox_params["relation"] = prox_params.pop("prox_method")        if prox_params:            rel = prox_params.get("relation", self._proximity.relation)            self._proximity._init_sparse_proximity(                prox_method=rel,                matrix_type=prox_params.get("matrix_type", self._proximity.matrix_type),                non_zero_diagonal=prox_params.get("non_zero_diagonal", self._proximity.non_zero_diagonal),                symm_mode=prox_params.get("symm_mode", self._proximity.symm_mode),                max_normalize=prox_params.get("max_normalize", self._proximity.max_normalize),            )            if "random_state" in prox_params:                self._proximity.random_state = prox_params["random_state"]        return self    def get_params(self, deep=True):        params = {}        try:            params.update(self._proximity.estimator.get_params(deep=deep))        except Exception:            pass        params.update({            "relation": self._proximity.relation,            "prox_method": self._proximity.relation,            "matrix_type": self._proximity.matrix_type,            "non_zero_diagonal": self._proximity.non_zero_diagonal,            "symm_mode": self._proximity.symm_mode,            "max_normalize": self._proximity.max_normalize,        })        return params    def phate(self, **kwargs):        return embed(self._proximity, method="phate", **kwargs)    def outlier_scores(self, *args, **kwargs):        return outlier_scores(self._proximity, *args, **kwargs)    def impute(self, *args, **kwargs):        return impute(self._proximity, *args, **kwargs)    def get_prototypes(self, *args, **kwargs):        return get_prototypes(self._proximity, *args, **kwargs)    def local_feature_importance(self, *args, **kwargs):        return local_feature_importance(self._proximity, *args, **kwargs)    def local_variable_importance(self, *args, **kwargs):        return local_feature_importance(self._proximity, *args, **kwargs)    def __getattr__(self, name):        return getattr(self._proximity, name)def compose_proximity(estimator_or_cls):    if isinstance(estimator_or_cls, type):        def _factory(*args, **kwargs):            relation = kwargs.pop("relation", kwargs.pop("prox_method", "rfgap"))            matrix_type = kwargs.pop("matrix_type", "sparse")            non_zero_diagonal = kwargs.pop("non_zero_diagonal", False)            symm_mode = kwargs.pop("symm_mode", None)            max_normalize = kwargs.pop("max_normalize", False)            random_state = kwargs.pop("random_state", None)            estimator = estimator_or_cls(*args, **kwargs)            prox = Proximity(                estimator,                relation=relation,                matrix_type=matrix_type,                non_zero_diagonal=non_zero_diagonal,                symm_mode=symm_mode,                max_normalize=max_normalize,                random_state=random_state,            )            return _LegacyProximityModel(prox)        return _factory    prox = Proximity(estimator_or_cls)    return _LegacyProximityModel(prox)

Vanilla RF-GAP assigns training-sample weights from bootstrap in-bag multiplicities within terminal leaves. Honest forests use one subset to learn split structure and a separate honest subset to estimate leaf predictions. Therefore the fitted leaf posterior is not the empirical distribution of all in-bag samples in the leaf. Honest-GAP instead distributes each fitted leaf/class mass across the honest estimation samples that contributed that class mass.

In [1]:
from pathlib import Pathimport inspectimport sysimport warningsimport numpy as npimport pandas as pdfrom scipy import sparsefrom sklearn.datasets import make_classificationfrom sklearn.model_selection import train_test_splitROOT = Path.cwd()if (ROOT / "forestgap").exists():    sys.path.insert(0, str(ROOT))elif (ROOT.parent / "forestgap").exists():    sys.path.insert(0, str(ROOT.parent))try:    from treeple import HonestForestClassifier    HAS_TREEPLE = True    TREEPLE_ERROR = Noneexcept Exception as exc:    HonestForestClassifier = None    HAS_TREEPLE = False    TREEPLE_ERROR = excif not HAS_TREEPLE:    print(f"Skipping HonestForest demo because treeple is unavailable: {TREEPLE_ERROR}")

In [2]:
def to_dense(mat):    return mat.toarray() if sparse.isspmatrix(mat) else np.asarray(mat)def one_hot(y, classes):    mapping = {cls: i for i, cls in enumerate(np.asarray(classes).tolist())}    y_idx = np.array([mapping[value] for value in y], dtype=np.int64)    return sparse.csc_matrix(        (np.ones(y_idx.shape[0]), (np.arange(y_idx.shape[0]), y_idx)),        shape=(y_idx.shape[0], len(classes)),    )def finite_rows(*arrays):    mask = None    for arr in arrays:        arr = np.asarray(arr, dtype=float)        finite = np.isfinite(arr) if arr.ndim == 1 else np.all(np.isfinite(arr), axis=1)        mask = finite if mask is None else (mask & finite)    return np.asarray(mask, dtype=bool)def diff_summary(name, lhs, rhs):    lhs = np.asarray(lhs, dtype=float)    rhs = np.asarray(rhs, dtype=float)    mask = finite_rows(lhs, rhs)    if not np.any(mask):        return {"comparison": name, "finite_rows": 0, "max_abs_diff": np.nan, "mean_abs_diff": np.nan}    diff = np.abs(lhs[mask] - rhs[mask])    return {        "comparison": name,        "finite_rows": int(mask.sum()),        "max_abs_diff": float(diff.max()),        "mean_abs_diff": float(diff.mean()),    }def honest_model_kwargs(*, prox_method, random_state, kernel_method=True, stratify=True):    sig = inspect.signature(HonestForestClassifier.__init__)    kwargs = {        "n_estimators": 80,        "random_state": random_state,        "prox_method": prox_method,        "matrix_type": "sparse",    }    optional = {        "bootstrap": True,        "oob_score": True,        "honest_fraction": 0.5,        "max_depth": 6,        "min_samples_leaf": 2,        "kernel_method": kernel_method,        "stratify": stratify,    }    for key, value in optional.items():        if key in sig.parameters:            kwargs[key] = value    return kwargs

In [3]:
if HAS_TREEPLE:    X, y = make_classification(        n_samples=260,        n_features=10,        n_informative=7,        n_redundant=1,        n_classes=3,        n_clusters_per_class=1,        class_sep=1.4,        random_state=201,    )    X_train, X_test, y_train, y_test = train_test_split(        X, y, test_size=0.25, stratify=y, random_state=202    )    ProxHonest = compose_proximity(HonestForestClassifier)    print(X_train.shape, X_test.shape, np.bincount(y_train))

(195, 10) (65, 10) [65 67 63]

## Vanilla RF-GAPUsing `prox_method="rfgap"` with an Honest forest now emits a warning. The adapter still computes ordinary RF-GAP, but those weights are not expected to reconstruct Honest forest predictions.

In [4]:
rows = []if HAS_TREEPLE:    with warnings.catch_warnings(record=True) as caught:        warnings.simplefilter("always")        rfgap = ProxHonest(**honest_model_kwargs(            prox_method="rfgap",            random_state=301,            kernel_method=True,            stratify=True,        ))        rfgap.fit(X_train, y_train)    print("Warnings:")    for warning in caught:        print(f"- {warning.message}")    rows.append(diff_summary(        "rfgap prox_predict(X_test) vs predict_proba(X_test)",        rfgap.prox_predict(X_test),        rfgap.predict_proba(X_test),    ))pd.DataFrame(rows)

Warnings:
- prox_method='rfgap' uses ordinary RF-GAP bootstrap semantics, which do not reconstruct HonestForestClassifier predictions. Use prox_method='honest_gap' for HonestForest prediction reconstruction.

,comparison,finite_rows,max_abs_diff,mean_abs_diff
0,rfgap prox_predict(X_test) vs predict_proba(X_...,65,0.097964,0.020933

## Honest-GAP`honest_gap` builds its training-side factor from the honest estimation subset and fitted leaf values. For test data, rows are normalized after extension so `prox_extend(X_test) @ y_one_hot` matches `predict_proba(X_test)`.

In [5]:
if HAS_TREEPLE:    honest_gap = ProxHonest(**honest_model_kwargs(        prox_method="honest_gap",        random_state=302,        kernel_method=True,        stratify=True,    ))    honest_gap.fit(X_train, y_train)    native_test = honest_gap.predict_proba(X_test)    prox_test = honest_gap.prox_predict(X_test)    matrix_test = to_dense(honest_gap.prox_extend(X_test)) @ one_hot(y_train, honest_gap.classes_)    rows.extend([        diff_summary("honest_gap prox_predict(X_test) vs predict_proba(X_test)", prox_test, native_test),        diff_summary("honest_gap prox_extend(X_test) @ y_one_hot vs predict_proba(X_test)", matrix_test, native_test),    ])pd.DataFrame(rows)

,comparison,finite_rows,max_abs_diff,mean_abs_diff
0,rfgap prox_predict(X_test) vs predict_proba(X_...,65,9.796371e-02,2.093274e-02
1,honest_gap prox_predict(X_test) vs predict_pro...,65,4.440892e-16,5.988799e-17
2,honest_gap prox_extend(X_test) @ y_one_hot vs ...,65,3.330669e-16,6.394458e-17

## OOB CaveatFor `kernel_method=True`, treeple's native Honest forest OOB output can be raw/count-like rather than probability-normalized. `honest_gap.prox_predict()` intentionally matches that native OOB scale for training/OOB predictions.

In [6]:
if HAS_TREEPLE:    native_oob = np.asarray(honest_gap.oob_decision_function_, dtype=float)    prox_oob = np.asarray(honest_gap.prox_predict(), dtype=float)    rows.append(diff_summary("honest_gap prox_predict() vs oob_decision_function_", prox_oob, native_oob))    finite = finite_rows(native_oob)    print("Finite OOB rows:", int(finite.sum()))    print("OOB row-sum range:", (float(np.nanmin(native_oob[finite].sum(axis=1))), float(np.nanmax(native_oob[finite].sum(axis=1)))))pd.DataFrame(rows)

Finite OOB rows: 180
OOB row-sum range: (12.76923076923077, 42.66666666666667)

,comparison,finite_rows,max_abs_diff,mean_abs_diff
0,rfgap prox_predict(X_test) vs predict_proba(X_...,65,9.796371e-02,2.093274e-02
1,honest_gap prox_predict(X_test) vs predict_pro...,65,4.440892e-16,5.988799e-17
2,honest_gap prox_extend(X_test) @ y_one_hot vs ...,65,3.330669e-16,6.394458e-17
3,honest_gap prox_predict() vs oob_decision_func...,180,1.752377e-06,2.206434e-07

## Probability-Scaled OOB ModeWith `kernel_method=False`, Honest-GAP uses per-tree leaf probabilities, so OOB rows match the native probability-scaled `oob_decision_function_` on finite rows.

In [7]:
if HAS_TREEPLE and "kernel_method" in inspect.signature(HonestForestClassifier.__init__).parameters:    honest_gap_prob = ProxHonest(**honest_model_kwargs(        prox_method="honest_gap",        random_state=303,        kernel_method=False,        stratify=True,    ))    honest_gap_prob.fit(X_train, y_train)    rows.append(diff_summary(        "honest_gap kernel_method=False prox_predict() vs oob_decision_function_",        honest_gap_prob.prox_predict(),        honest_gap_prob.oob_decision_function_,    ))pd.DataFrame(rows).sort_values("comparison").reset_index(drop=True)

,comparison,finite_rows,max_abs_diff,mean_abs_diff
0,honest_gap kernel_method=False prox_predict() ...,181,4.855087e-08,7.169297e-09
1,honest_gap prox_extend(X_test) @ y_one_hot vs ...,65,3.330669e-16,6.394458e-17
2,honest_gap prox_predict() vs oob_decision_func...,180,1.752377e-06,2.206434e-07
3,honest_gap prox_predict(X_test) vs predict_pro...,65,4.440892e-16,5.988799e-17
4,rfgap prox_predict(X_test) vs predict_proba(X_...,65,9.796371e-02,2.093274e-02

In [8]:
honest_gap_prob.oob_decision_function_

array([[0.03417156, 0.9393921 , 0.02643634],
       [0.74142781, 0.06869778, 0.18987441],
       [0.12804985, 0.78125802, 0.09069212],
       [0.8652696 , 0.1025382 , 0.0321922 ],
       [0.05223051, 0.82908381, 0.11868568],
       [0.75578843, 0.12338103, 0.12083054],
       [0.76887633, 0.16011076, 0.07101291],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [0.7921421 , 0.15879856, 0.04905934],
       [0.69485267, 0.08336946, 0.22177787],
       [0.79977271, 0.07638694, 0.12384035],
       [0.85194853, 0.09094422, 0.05710725],
       [0.03959747, 0.79351942, 0.16688312],
       [0.0431978 , 0.93179324, 0.02500896],
       [0.26433085, 0.01501502, 0.72065414],
       [0.68446725, 0.24993937, 0.06559338],
       [0.8944162 , 0.06762439, 0.03795941],
       [0.03063439, 0.05110329, 0.91826232],
       [0.82867141, 0.09748412, 0.07384447],
       [0.05933014, 0.8557711 , 0.08489876],
       [0.80346496, 0.10557793, 0.09095711],
       [0.66542031, 0.07245462, 0.26212506],
       [0.08002493, 0.17180173, 0.74817333],
       [0.74579811, 0.06703932, 0.18716257],
       [0.05772764, 0.13840014, 0.80387222],
       [0.215289  , 0.77428546, 0.01042553],
       [0.07742281, 0.49513671, 0.42744048],
       [0.08839604, 0.8801945 , 0.03140947],
       [0.03867354, 0.91688787, 0.04443859],
       [0.1180978 , 0.06356101, 0.81834118],
       [0.15724157, 0.02510823, 0.8176502 ],
       [0.11125602, 0.06643817, 0.82230581],
       [0.08322668, 0.03782767, 0.87894565],
       [0.06543128, 0.11494755, 0.81962118],
       [0.10939698, 0.46231365, 0.42828937],
       [0.0677373 , 0.87488901, 0.0573737 ],
       [       nan,        nan,        nan],
       [0.03198465, 0.94545969, 0.02255567],
       [0.64545613, 0.10633487, 0.24820899],
       [0.23733146, 0.08549484, 0.6771737 ],
       [0.02392159, 0.93581885, 0.04025955],
       [0.7244406 , 0.1960413 , 0.0795181 ],
       [0.04954723, 0.0599375 , 0.89051527],
       [0.05913968, 0.01683383, 0.92402649],
       [0.73954923, 0.07334666, 0.18710411],
       [0.86534985, 0.10213052, 0.03251963],
       [0.88494426, 0.08691166, 0.02814407],
       [0.03916774, 0.87644467, 0.08438759],
       [0.83634953, 0.10642674, 0.05722372],
       [       nan,        nan,        nan],
       [0.70352103, 0.03001612, 0.26646285],
       [0.69845699, 0.038225  , 0.26331802],
       [0.05672432, 0.30300175, 0.64027393],
       [0.0199396 , 0.78591594, 0.19414446],
       [0.06240408, 0.90971944, 0.02787648],
       [0.03697969, 0.11334451, 0.84967581],
       [0.03962952, 0.92938163, 0.03098885],
       [0.28514997, 0.15355339, 0.56129664],
       [0.12968269, 0.05225586, 0.81806145],
       [0.01315789, 0.81748769, 0.16935441],
       [0.08063903, 0.07605207, 0.8433089 ],
       [0.03452607, 0.09263217, 0.87284176],
       [0.4702854 , 0.11031139, 0.41940321],
       [0.04404919, 0.93321437, 0.02273644],
       [0.7955429 , 0.13924403, 0.06521307],
       [0.28864848, 0.10336303, 0.60798849],
       [0.0368456 , 0.90259814, 0.06055626],
       [0.03919087, 0.92809961, 0.03270951],
       [0.15160222, 0.06926176, 0.77913602],
       [       nan,        nan,        nan],
       [0.04320214, 0.09026666, 0.8665312 ],
       [       nan,        nan,        nan],
       [0.87673418, 0.05549157, 0.06777425],
       [0.11264107, 0.04753689, 0.83982204],
       [0.75421142, 0.1758352 , 0.06995338],
       [0.73232719, 0.21980774, 0.04786507],
       [0.26367271, 0.10226557, 0.63406172],
       [0.81589455, 0.09677636, 0.08732909],
       [0.66917542, 0.13802501, 0.19279956],
       [0.74567492, 0.1050959 , 0.14922919],
       [0.81927692, 0.09022903, 0.09049405],
       [0.01996507, 0.92443902, 0.05559591],
       [0.02277993, 0.15030071, 0.82691935],
       [0.0607214 , 0.90831366, 0.03096493],
       [0.03352125, 0.10568778, 0.86079097],
       [0.8815847 , 0.0452066 , 0.0732087 ],
       [0.12667617, 0.03256626, 0.84075757],
       [0.85654216, 0.06956419, 0.07389365],
       [0.00885273, 0.96093995, 0.03020732],
       [0.05663265, 0.07313659, 0.87023076],
       [0.07333333, 0.57220721, 0.35445946],
       [0.81250275, 0.09531152, 0.09218573],
       [0.05126031, 0.79186928, 0.15687041],
       [0.8143374 , 0.14036805, 0.04529455],
       [0.19472531, 0.77575652, 0.02951817],
       [       nan,        nan,        nan],
       [       nan,        nan,        nan],
       [0.72371253, 0.18075756, 0.0955299 ],
       [0.00810658, 0.94286051, 0.04903291],
       [0.04545455, 0.65821529, 0.29633017],
       [0.15158212, 0.70518647, 0.14323141],
       [0.03034047, 0.02423234, 0.9454272 ],
       [0.04131826, 0.90871475, 0.049967  ],
       [       nan,        nan,        nan],
       [0.06418646, 0.0767245 , 0.85908903],
       [0.02793442, 0.0673859 , 0.90467968],
       [0.02273515, 0.05536906, 0.92189578],
       [0.84448474, 0.06126723, 0.09424804],
       [0.74799644, 0.1926559 , 0.05934765],
       [0.24598726, 0.09078548, 0.66322726],
       [0.20382585, 0.31214263, 0.48403152],
       [0.        , 0.95678601, 0.04321399],
       [       nan,        nan,        nan],
       [0.12566166, 0.82167975, 0.05265859],
       [0.85904806, 0.0991015 , 0.04185045],
       [0.05059161, 0.08492681, 0.86448159],
       [0.86556133, 0.06154277, 0.0728959 ],
       [0.12677137, 0.07637034, 0.79685829],
       [0.15701429, 0.03516728, 0.80781843],
       [0.0751634 , 0.86210707, 0.06272954],
       [0.37037037, 0.42194656, 0.20768307],
       [0.88932029, 0.07033032, 0.04034939],
       [0.19117806, 0.05053896, 0.75828299],
       [0.2492146 , 0.4441644 , 0.30662099],
       [0.86926229, 0.10102514, 0.02971257],
       [0.04241671, 0.93927971, 0.01830357],
       [0.17213095, 0.8103301 , 0.01753895],
       [0.47678973, 0.42641787, 0.09679239],
       [0.79214519, 0.15699263, 0.05086218],
       [0.03866533, 0.05710361, 0.90423106],
       [0.09576446, 0.84493406, 0.05930147],
       [0.88315342, 0.04106148, 0.07578511],
       [0.06760141, 0.84926713, 0.08313146],
       [0.92732005, 0.05207169, 0.02060827],
       [0.03030303, 0.90893058, 0.06076639],
       [0.42047418, 0.35577412, 0.22375171],
       [0.89073428, 0.0701535 , 0.03911222],
       [0.84409536, 0.07254121, 0.08336342],
       [0.04328122, 0.9302754 , 0.02644338],
       [0.4194191 , 0.18993908, 0.39064181],
       [0.045546  , 0.07899458, 0.87545942],
       [0.05632571, 0.93109865, 0.01257564],
       [0.17361012, 0.08678821, 0.73960167],
       [0.76467879, 0.06992897, 0.16539225],
       [0.0283436 , 0.04074391, 0.93091249],
       [0.03120461, 0.10335513, 0.86544026],
       [0.03879697, 0.09407446, 0.86712857],
       [0.75186851, 0.13265114, 0.11548035],
       [0.07962274, 0.90769661, 0.01268065],
       [0.86884195, 0.0537027 , 0.07745536],
       [0.04744506, 0.06498936, 0.88756558],
       [0.03491919, 0.9253582 , 0.0397226 ],
       [0.04058139, 0.9319791 , 0.02743951],
       [       nan,        nan,        nan],
       [0.04236813, 0.74457047, 0.2130614 ],
       [0.17312241, 0.05325566, 0.77362193],
       [0.11270264, 0.07513926, 0.81215809],
       [0.07363225, 0.90263856, 0.02372919],
       [0.78017714, 0.08857562, 0.13124724],
       [0.1922804 , 0.08885766, 0.71886194],
       [0.83327225, 0.10675518, 0.05997258],
       [0.01259653, 0.92876373, 0.05863974],
       [0.78518004, 0.0623881 , 0.15243186],
       [0.03806971, 0.22924883, 0.73268145],
       [0.02080831, 0.93469704, 0.04449465],
       [0.0929236 , 0.78430514, 0.12277126],
       [0.78550222, 0.17230726, 0.04219052],
       [0.03794554, 0.91961853, 0.04243593],
       [0.90479299, 0.06023306, 0.03497394],
       [0.05904217, 0.10977859, 0.83117925],
       [0.05861244, 0.91165872, 0.02972884],
       [0.04285173, 0.05710068, 0.90004759],
       [0.83137649, 0.14111155, 0.02751196],
       [0.01974448, 0.08349075, 0.89676477],
       [0.85877616, 0.09795611, 0.04326774],
       [0.83631171, 0.11011686, 0.05357143],
       [0.86650131, 0.07906201, 0.05443668],
       [0.03403845, 0.05073028, 0.91523128],
       [0.06684504, 0.90671967, 0.02643529],
       [0.27167806, 0.69583531, 0.03248663],
       [0.81603183, 0.13640026, 0.04756791],
       [0.08429278, 0.04977095, 0.86593627],
       [0.83471033, 0.0828815 , 0.08240817],
       [0.11174234, 0.86433933, 0.02391833],
       [       nan,        nan,        nan],
       [0.75350695, 0.16520524, 0.08128781],
       [0.14618672, 0.059308  , 0.79450528],
       [0.0074121 , 0.67985105, 0.31273685],
       [0.77489123, 0.17938011, 0.04572866],
       [0.89820642, 0.06156828, 0.0402253 ],
       [0.1820197 , 0.14640023, 0.67158007],
       [       nan,        nan,        nan],
       [0.01065476, 0.93760194, 0.0517433 ]])

In [9]:
honest_gap_prob.prox_predict()

array([[0.03417156, 0.9393921 , 0.02643634],
       [0.74142781, 0.06869778, 0.18987441],
       [0.12804986, 0.78125806, 0.09069213],
       [0.8652696 , 0.1025382 , 0.0321922 ],
       [0.05223051, 0.82908385, 0.11868568],
       [0.75578847, 0.12338104, 0.12083055],
       [0.76887637, 0.16011077, 0.07101292],
       [0.42562876, 0.04757785, 0.46796986],
       [0.05940733, 0.39250501, 0.49545608],
       [0.16467485, 0.61730683, 0.16538675],
       [0.79214214, 0.15879857, 0.04905934],
       [0.69485269, 0.08336946, 0.22177788],
       [0.79977271, 0.07638694, 0.12384035],
       [0.85194853, 0.09094422, 0.05710725],
       [0.03959747, 0.79351945, 0.16688312],
       [0.0431978 , 0.93179325, 0.02500896],
       [0.26433086, 0.01501502, 0.72065416],
       [0.68446727, 0.24993938, 0.06559339],
       [0.89441621, 0.0676244 , 0.03795941],
       [0.03063439, 0.0511033 , 0.91826233],
       [0.82867141, 0.09748412, 0.07384447],
       [0.05933015, 0.85577112, 0.08489876],
       [0.803465  , 0.10557793, 0.09095712],
       [0.66542035, 0.07245463, 0.26212508],
       [0.08002494, 0.17180174, 0.74817337],
       [0.74579812, 0.06703932, 0.18716257],
       [0.05772764, 0.13840014, 0.80387223],
       [0.21528902, 0.7742855 , 0.01042553],
       [0.07742281, 0.49513672, 0.42744049],
       [0.08839604, 0.88019452, 0.03140947],
       [0.03867354, 0.91688787, 0.04443859],
       [0.1180978 , 0.06356101, 0.81834118],
       [0.15724158, 0.02510823, 0.81765023],
       [0.11125602, 0.06643817, 0.82230583],
       [0.08322668, 0.03782767, 0.87894565],
       [0.06543128, 0.11494755, 0.81962118],
       [0.10939698, 0.46231365, 0.42828937],
       [0.0677373 , 0.87488902, 0.0573737 ],
       [0.01560458, 0.84352898, 0.08204292],
       [0.03198465, 0.94545972, 0.02255567],
       [0.64545613, 0.10633487, 0.24820899],
       [0.23733146, 0.08549485, 0.67717371],
       [0.0239216 , 0.93581886, 0.04025955],
       [0.7244406 , 0.1960413 , 0.0795181 ],
       [0.04954723, 0.0599375 , 0.89051531],
       [0.05913968, 0.01683383, 0.92402649],
       [0.73954925, 0.07334667, 0.18710412],
       [0.86534987, 0.10213052, 0.03251963],
       [0.88494426, 0.08691166, 0.02814407],
       [0.03916774, 0.87644469, 0.08438759],
       [0.83634953, 0.10642674, 0.05722372],
       [0.11411911, 0.0483739 , 0.78195144],
       [0.70352105, 0.03001612, 0.26646286],
       [0.69845699, 0.038225  , 0.26331802],
       [0.05672432, 0.30300176, 0.64027394],
       [0.0199396 , 0.78591594, 0.19414446],
       [0.06240408, 0.90971945, 0.02787648],
       [0.03697969, 0.11334451, 0.84967581],
       [0.03962952, 0.92938164, 0.03098885],
       [0.28514998, 0.1535534 , 0.56129666],
       [0.12968269, 0.05225586, 0.81806146],
       [0.01315789, 0.81748769, 0.16935441],
       [0.08063904, 0.07605207, 0.84330894],
       [0.03452607, 0.09263217, 0.8728418 ],
       [0.4702854 , 0.11031139, 0.41940321],
       [0.0440492 , 0.9332144 , 0.02273644],
       [0.79554294, 0.13924404, 0.06521308],
       [0.28864848, 0.10336303, 0.60798849],
       [0.0368456 , 0.90259815, 0.06055627],
       [0.03919087, 0.92809963, 0.03270951],
       [0.15160223, 0.06926176, 0.77913602],
       [0.75978783, 0.14376804, 0.05477749],
       [0.04320214, 0.09026666, 0.86653124],
       [0.13978328, 0.7784026 , 0.02625857],
       [0.87673419, 0.05549157, 0.06777425],
       [0.11264107, 0.04753689, 0.83982207],
       [0.75421146, 0.17583521, 0.06995338],
       [0.73232722, 0.21980775, 0.04786507],
       [0.26367272, 0.10226557, 0.63406174],
       [0.81589456, 0.09677636, 0.08732909],
       [0.66917543, 0.13802502, 0.19279957],
       [0.74567495, 0.1050959 , 0.14922919],
       [0.81927692, 0.09022903, 0.09049405],
       [0.01996507, 0.92443902, 0.05559591],
       [0.02277993, 0.15030072, 0.8269194 ],
       [0.0607214 , 0.90831366, 0.03096493],
       [0.03352125, 0.10568778, 0.86079098],
       [0.88158473, 0.0452066 , 0.0732087 ],
       [0.12667617, 0.03256626, 0.8407576 ],
       [0.85654218, 0.06956419, 0.07389366],
       [0.00885273, 0.96093999, 0.03020732],
       [0.05663265, 0.07313659, 0.87023077],
       [0.07333334, 0.57220724, 0.35445947],
       [0.81250275, 0.09531152, 0.09218573],
       [0.05126031, 0.79186929, 0.15687041],
       [0.81433741, 0.14036806, 0.04529455],
       [0.19472532, 0.77575655, 0.02951817],
       [0.12578902, 0.14970556, 0.67187385],
       [0.14463509, 0.50778173, 0.29495161],
       [0.72371254, 0.18075756, 0.0955299 ],
       [0.00810658, 0.94286055, 0.04903291],
       [0.04545455, 0.65821531, 0.29633018],
       [0.15158212, 0.70518647, 0.14323141],
       [0.03034047, 0.02423234, 0.94542721],
       [0.04131826, 0.90871477, 0.049967  ],
       [0.08585918, 0.25902587, 0.59261495],
       [0.06418646, 0.0767245 , 0.85908903],
       [0.02793442, 0.0673859 , 0.90467972],
       [0.02273515, 0.05536907, 0.92189581],
       [0.84448474, 0.06126723, 0.09424804],
       [0.74799646, 0.19265591, 0.05934766],
       [0.24598726, 0.09078548, 0.66322726],
       [0.20382586, 0.31214265, 0.48403154],
       [0.        , 0.95678603, 0.043214  ],
       [0.06262096, 0.42004685, 0.43399889],
       [0.12566166, 0.82167975, 0.05265859],
       [0.85904809, 0.0991015 , 0.04185045],
       [0.05059161, 0.08492681, 0.86448159],
       [0.86556136, 0.06154277, 0.0728959 ],
       [0.12677137, 0.07637034, 0.7968583 ],
       [0.15701429, 0.03516728, 0.80781843],
       [0.0751634 , 0.86210707, 0.06272954],
       [0.37037039, 0.42194658, 0.20768308],
       [0.88932029, 0.07033032, 0.04034939],
       [0.19117806, 0.05053896, 0.75828299],
       [0.24921462, 0.44416443, 0.30662101],
       [0.86926229, 0.10102514, 0.02971257],
       [0.04241671, 0.93927971, 0.01830357],
       [0.17213096, 0.81033014, 0.01753895],
       [0.47678975, 0.42641789, 0.09679239],
       [0.79214521, 0.15699264, 0.05086218],
       [0.03866533, 0.05710361, 0.90423107],
       [0.09576447, 0.84493409, 0.05930148],
       [0.88315343, 0.04106148, 0.07578511],
       [0.06760141, 0.84926713, 0.08313146],
       [0.92732005, 0.05207169, 0.02060827],
       [0.03030303, 0.90893058, 0.06076639],
       [0.42047418, 0.35577412, 0.22375171],
       [0.89073428, 0.0701535 , 0.03911222],
       [0.84409541, 0.07254122, 0.08336343],
       [0.04328122, 0.93027541, 0.02644338],
       [0.41941912, 0.18993909, 0.39064183],
       [0.045546  , 0.07899459, 0.87545945],
       [0.05632571, 0.93109866, 0.01257564],
       [0.17361013, 0.08678822, 0.7396017 ],
       [0.76467881, 0.06992897, 0.16539225],
       [0.02834361, 0.04074391, 0.93091254],
       [0.03120462, 0.10335513, 0.86544029],
       [0.03879697, 0.09407446, 0.8671286 ],
       [0.75186855, 0.13265114, 0.11548036],
       [0.07962275, 0.90769665, 0.01268065],
       [0.86884195, 0.0537027 , 0.07745536],
       [0.04744506, 0.06498936, 0.88756559],
       [0.03491919, 0.9253582 , 0.0397226 ],
       [0.04058139, 0.93197913, 0.02743951],
       [0.23172366, 0.47369105, 0.23576176],
       [0.04236813, 0.74457048, 0.2130614 ],
       [0.17312242, 0.05325566, 0.77362196],
       [0.11270265, 0.07513927, 0.81215814],
       [0.07363225, 0.90263858, 0.0237292 ],
       [0.78017715, 0.08857562, 0.13124724],
       [0.1922804 , 0.08885766, 0.71886194],
       [0.83327225, 0.10675518, 0.05997258],
       [0.01259653, 0.92876374, 0.05863974],
       [0.78518007, 0.0623881 , 0.15243187],
       [0.03806972, 0.22924884, 0.73268148],
       [0.02080831, 0.93469705, 0.04449465],
       [0.0929236 , 0.78430514, 0.12277126],
       [0.78550223, 0.17230726, 0.04219052],
       [0.03794554, 0.91961853, 0.04243593],
       [0.904793  , 0.06023306, 0.03497394],
       [0.05904217, 0.10977859, 0.83117925],
       [0.05861244, 0.91165875, 0.02972884],
       [0.04285174, 0.05710068, 0.90004763],
       [0.83137651, 0.14111156, 0.02751196],
       [0.01974448, 0.08349075, 0.89676479],
       [0.85877617, 0.09795611, 0.04326774],
       [0.83631171, 0.11011686, 0.05357143],
       [0.86650136, 0.07906202, 0.05443668],
       [0.03403845, 0.05073028, 0.91523132],
       [0.06684504, 0.90671968, 0.02643529],
       [0.27167806, 0.69583531, 0.03248663],
       [0.81603186, 0.13640027, 0.04756791],
       [0.08429278, 0.04977095, 0.86593628],
       [0.83471035, 0.0828815 , 0.08240817],
       [0.11174234, 0.86433935, 0.02391833],
       [0.22061514, 0.60039407, 0.1289908 ],
       [0.75350696, 0.16520524, 0.08128781],
       [0.14618672, 0.059308  , 0.79450529],
       [0.0074121 , 0.67985107, 0.31273686],
       [0.77489126, 0.17938012, 0.04572866],
       [0.89820643, 0.06156828, 0.0402253 ],
       [0.1820197 , 0.14640023, 0.67158007],
       [0.39640729, 0.15596299, 0.40001069],
       [0.01065476, 0.93760195, 0.0517433 ]])